### ISSUE TITLE
Is this being used?

### ISSUE THREAD

**Issue by decentralgabe** [w3c/webpayments-method-identifiers#74]
Are there any registered payment method identifiers (besides URIs)? How does one go about registering one? Are there examples of this being used in a real-world scenario?

**Comment by ianbjacobs** [comment]
@decentralgabe,

The PMI specification says "A standardized payment method is a payment method that has undergone standardization at the W3C, and is listed in this registry." Since the Web Payments Working Group manages the PMI specification, it decides what to  include in the registry.

[Secure Payment Confirmation](https://w3c.github.io/secure-payment-confirmation/) defines a standardized payment method identifier. However, it is not yet a Recommendation, so we have not included it in the PMI registry.

**Comment by thereisnogabe** [comment]
thanks @ianbjacobs !
